# Generated by Django 6.0.2 on 2026-06-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='confidence',
            field=models.FloatField(blank=True, help_text='AI detection confidence percentage', null=True),
        ),
    ]
