# Generated by Django 6.0.2 on 2026-06-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StainApp', '0003_scan_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(default='INFO', max_length=20)),
                ('user', models.CharField(default='System', max_length=100)),
                ('event_action', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scan',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
